// <auto-generated />
using AssignmentPromact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssignmentPromact.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200207115233_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AssignmentPromact.Models.Posts", b =>
                {
                    b.Property<int>("Post_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Comments")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Post_Id");

                    b.ToTable("posts");

                    b.HasData(
                        new
                        {
                            Post_Id = 1,
                            Comments = 6,
                            Likes = 5,
                            Post = "This Is My First Post...Thankyou",
                            userID = "jha@06"
                        },
                        new
                        {
                            Post_Id = 2,
                            Comments = 8,
                            Likes = 5,
                            Post = "This Is Shusnavi's First Post...Thankyou",
                            userID = "shus@16"
                        },
                        new
                        {
                            Post_Id = 3,
                            Comments = 5,
                            Likes = 9,
                            Post = "Thankyou For Reading My First Post",
                            userID = "sweta@26"
                        },
                        new
                        {
                            Post_Id = 4,
                            Comments = 16,
                            Likes = 25,
                            Post = "Stay Still...There's More To Come..",
                            userID = "visu@21"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
